baseURL = 'https://xianzhiw.github.io/'
# languageCode = 'en-us'
# title = 'Xianzhi Wang'
# theme = 'hello-friend-ng'



# baseurl      = "localhost"
title        = "Xianzhi Wang"
languageCode = "en-us"
# theme        = "hello-friend-ng"
paginate     = 10

theme = 'lugo'
