# languageCode = 'en-us'
# title = 'Xianzhi Wang'
# theme = 'hello-friend-ng'
# baseurl      = "localhost"
# languageCode = "en-us"
# theme        = "hello-friend-ng"



title        = "Xianzhi Wang"
baseURL = 'https://xianzhiw.github.io/'
# baseURL = 'https://example.org'
languageCode = 'en-us'
publishDir = "./docs/"

theme = 'hugo-xmin'
# theme = 'lugo'
# paginate     = 10
